### ISSUE TITLE
Revisió erros de logs

### ISSUE THREAD

**Issue by sandreu-limit** [GovernIB/notib#203]
S'han detectat tot un seguit d'errors que es repeteixen amb freqüència als logs.
Es revisaran els diferents errors per veure quin tractament se n'ha de fer de cada un d'ells.

**Comment by sandreu-limit** [comment]
Quan es produeix algun error al intentar descarregar un fitxer, enlloc de mostrar un error controlat, es mostra una pantalla amb un error 500. --> #209

**Comment by sandreu-limit** [comment]
Error al crear assentament registral:
`2020-05-21 00:02:14,864 INFO  [es.caib.notib.core.helper.RegistreNotificaHelper] (taskScheduler-3)  >>> Nou assentament registral...
2020-05-21 00:02:14,864 ERROR [es.caib.notib.core.helper.RegistreNotificaHelper] (taskScheduler-3) 
java.lang.NullPointerException
        at es.caib.notib.core.helper.PluginHelper.notificacioEnviamentsToAsientoRegistralBean(PluginHelper.java:1020)
        at es.caib.notib.core.helper.RegistreNotificaHelper.realitzarProcesRegistrarNotificar(RegistreNotificaHelper.java:153)
        at es.caib.notib.core.service.NotificacioServiceImpl.registrarNotificar(NotificacioServiceImpl.java:915)`

L'error és degut a que s'obté sempre l'oficina configurada al procediment.
Aquest error el resolem a la tasca #207

**Comment by sandreu-limit** [comment]
Error recurrent de connexió tancada 
`2020-05-21 09:47:14,788 WARN  [org.hibernate.util.JDBCExceptionReporter] (taskScheduler-7) SQL Error: 17008, SQLState: 08003
2020-05-21 09:47:14,788 ERROR [org.hibernate.util.JDBCExceptionReporter] (taskScheduler-7) Conexión cerrada
2020-05-21 09:47:14,789 ERROR [org.hibernate.ejb.AbstractEntityManagerImpl] (taskScheduler-7) Unable to mark for rollback on PersistenceException: 
java.lang.IllegalStateException: [com.arjuna.ats.internal.jta.transaction.arjunacore.nosuchtx] [com.arjuna.ats.internal.jta.transaction.arjunacore.nosuchtx] No such transaction!
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.setRollbackOnly(BaseTransaction.java:191)
        at com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.setRollbackOnly(BaseTransactionManagerDelegate.java:123)`

L'error és degut a que hi ha algun troç de codi que s'executa fora d'una transacció.
Aquest error el resolem a la tasca #202

**Comment by sandreu-limit** [comment]
Error recurrent enviant a registre: 
```
2020-05-28 02:23:47,941 INFO  [es.caib.notib.core.helper.RegistreNotificaHelper] (taskScheduler-7)  >>> Nou assentament registral...
2020-05-28 02:23:47,941 ERROR [es.caib.notib.core.helper.RegistreNotificaHelper] (taskScheduler-7) 
java.lang.NullPointerException
	at es.caib.notib.core.helper.PluginHelper.notificacioEnviamentsToAsientoRegistralBean(PluginHelper.java:1020)
	at es.caib.notib.core.helper.RegistreNotificaHelper.realitzarProcesRegistrarNotificar(RegistreNotificaHelper.java:153)
	at es.caib.notib.core.service.NotificacioServiceImpl.registrarNotificar(NotificacioServiceImpl.java:919)
	at es.caib.notib.core.service.NotificacioServiceImpl.notificacioRegistrar(NotificacioServiceImpl.java:982)
```

S'ha detectat que depenent del punt en que es produïa un error, no s'actualitzava el comptador de reintents d'enviament a registre. Això feia que els enviaments s'intentassin enviar a registre de forma indefinida, provocant molts errors als logs, i una quantitat de peticions innecessària.

**Comment by sandreu-limit** [comment]
Error recurrent consultant estat de notificació:
```
2020-05-28 02:19:44,987 ERROR [es.caib.notib.core.helper.NotificaV2Helper] (taskScheduler-6) Error al consultar l'estat d'un enviament fet amb NotificaV2 (notificacioId=42002, notificaIdentificador=22148335dd6a4085baf2)
javax.xml.ws.soap.SOAPFaultException: No se ha podido recuperar el contenido del documento
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:146)
	at com.sun.proxy.$Proxy822.infoEnvioV2(Unknown Source)
	at es.caib.notib.core.helper.NotificaV2Helper.enviamentRefrescarEstat(NotificaV2Helper.java:219)
	at es.caib.notib.core.helper.NotificaHelper.enviamentRefrescarEstat(NotificaHelper.java:42)
```
S'ha detectat que quan hi ha algun problema amb una notificació, de manera que notifica retorna un error cada cop que es consulta, aquesta notificació es continua consultant de manera indefinida, afegint peticions innecessàries.
Aquest error el resolem a la tasca #210
