### ISSUE TITLE
Error consultant arxiu de la gestió documental

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#487]
Al monitor d'integracions apareixen molts errors relacionats amb l'arxiu dins la pipella "Gestió documental"

![imatge](https://user-images.githubusercontent.com/58417501/111151531-dbd63c00-858f-11eb-975e-385818c00a4b.png)

```
es.caib.notib.plugin.SistemaExternException: No s'ha pogut llegir l'arxiu (id=1614096533060)
	at es.caib.notib.plugin.gesdoc.GestioDocumentalPluginFilesystem.get(GestioDocumentalPluginFilesystem.java:102)
	at es.caib.notib.core.helper.PluginHelper.gestioDocumentalGet(PluginHelper.java:860)
	at es.caib.notib.core.helper.NotificaV2Helper.generarAltaRemesaEnvios(NotificaV2Helper.java:428)
	at es.caib.notib.core.helper.NotificaV2Helper.enviaNotificacio(NotificaV2Helper.java:372)
	at es.caib.notib.core.helper.NotificaV2Helper.notificacioEnviar(NotificaV2Helper.java:111)
	at es.caib.notib.core.helper.NotificaV2Helper$$FastClassBySpringCGLIB$$d8ebda6b.invoke()
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
	at es.caib.notib.core.helper.NotificaV2Helper$$EnhancerBySpringCGLIB$$19f30e8f.notificacioEnviar()
	at es.caib.notib.core.helper.NotificaHelper.notificacioEnviar(NotificaHelper.java:32)
	at es.caib.notib.core.service.NotificacioServiceImpl.notificacioEnviar(NotificacioServiceImpl.java:1759)
	at sun.reflect.GeneratedMethodAccessor1294.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy877.notificacioEnviar(Unknown Source)
	at es.caib.notib.core.service.SchedulledServiceImpl.notificaEnviamentsRegistrats(SchedulledServiceImpl.java:98)
	at sun.reflect.GeneratedMethodAccessor1290.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: es.caib.notib.plugin.SistemaExternException: No s'ha trobat l'arxiu (id=1614096533060)
	at es.caib.notib.plugin.gesdoc.GestioDocumentalPluginFilesystem.get(GestioDocumentalPluginFilesystem.java:98)
	... 42 more
```

**Comment by acuevas-dgtic** [comment]
Ara hi ha alguns que funcionen i d'altres que no. Per exemple, no troba notificacions/1615972075790 i si que existeix dins del directori notificacions

![imatge](https://user-images.githubusercontent.com/58417501/111484130-c0a53100-8735-11eb-8b6e-120fb2f9f76b.png)

**Comment by josepg-limit** [comment]
ahora fallaran las que se han creado en las prerelease anteriores de esta version. 
Ahora todos los documentos tendran un identificador con el siguiente formato "1615849464678/1615989963292". Las que tienen un identificador con el formato "notificiacions/1615989963292" no deben funcionar porque los irá a buscar a la carpeta notificacions/notificiacions/1615989963292.

Los documentos de versiones anteriores seguiran funcionando

**Comment by acuevas-dgtic** [comment]
Ara pareix correcte. Tanco la issue
