### ISSUE TITLE
Error quan s'intenta notificar un csv que ve de l'antiga custodia

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/notib#496]
2021-03-30 12:18:37,922 ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler] (taskScheduler-3) Unexpected error occurred in scheduled task.
es.caib.notib.core.api.exception.RegistreNotificaException: Error al plugin d'arxiu digital: no s'ha pogut obtenir el codument amb identificador: csv:1616591456787-279937987-7864047978756099037
	at es.caib.notib.core.helper.RegistreNotificaHelper.realitzarProcesRegistrar(RegistreNotificaHelper.java:122)
	at es.caib.notib.core.service.NotificacioServiceImpl.registrarNotificar(NotificacioServiceImpl.java:1592)
	at es.caib.notib.core.service.NotificacioServiceImpl.notificacioRegistrar(NotificacioServiceImpl.java:1745)
	at sun.reflect.GeneratedMethodAccessor932.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy431.notificacioRegistrar(Unknown Source)
	at es.caib.notib.core.service.SchedulledServiceImpl.registrarEnviamentsPendents(SchedulledServiceImpl.java:71)
	at sun.reflect.GeneratedMethodAccessor1468.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: es.caib.notib.core.api.exception.SistemaExternException: Error al plugin d'arxiu digital: no s'ha pogut obtenir el codument amb identificador: csv:1616591456787-279937987-7864047978756099037
	at es.caib.notib.core.helper.PluginHelper.documentToAnexoWs(PluginHelper.java:1559)
	at es.caib.notib.core.helper.PluginHelper.notificacioEnviamentsToAsientoRegistralBean(PluginHelper.java:1852)
	at es.caib.notib.core.helper.PluginHelper$$FastClassBySpringCGLIB$$9dfa46b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	at es.caib.notib.core.helper.PluginHelper$$EnhancerBySpringCGLIB$$6710c1c9.notificacioEnviamentsToAsientoRegistralBean(<generated>)
	at es.caib.notib.core.helper.RegistreNotificaHelper.crearAssentamentRegistralPerNotificacio(RegistreNotificaHelper.java:168)
	at es.caib.notib.core.helper.RegistreNotificaHelper.realitzarProcesRegistrar(RegistreNotificaHelper.java:108)
	... 27 more
Caused by: es.caib.plugins.arxiu.api.ArxiuException: S'ha produit un error obtenent els detalls del document: 1616591456787-279937987-7864047978756099037
	at es.caib.notib.plugin.arxiu.ArxiuPluginConcsvImpl.documentDetallsCsv(ArxiuPluginConcsvImpl.java:60)
	at es.caib.notib.plugin.arxiu.ArxiuPluginConcsvImpl.documentDetalls(ArxiuPluginConcsvImpl.java:43)
	at es.caib.notib.core.helper.PluginHelper.arxiuDocumentConsultar(PluginHelper.java:715)
	at es.caib.notib.core.helper.PluginHelper.documentToAnexoWs(PluginHelper.java:1497)
	... 34 more
Caused by: es.caib.plugins.arxiu.api.ArxiuException: S'ha produit un error generant la versió imprimible del document
	at es.caib.notib.plugin.arxiu.ArxiuPluginConcsvImpl.documentMetadadesCsv(ArxiuPluginConcsvImpl.java:211)
	at es.caib.notib.plugin.arxiu.ArxiuPluginConcsvImpl.documentDetallsCsv(ArxiuPluginConcsvImpl.java:56)
	... 37 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: GET https://csv.caib.es/concsv/rest/metadata/1616591456787-279937987-7864047978756099037 returned a response status of 500 Internal Server Error
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
	at es.caib.notib.plugin.arxiu.ArxiuPluginConcsvImpl.documentMetadadesCsv(ArxiuPluginConcsvImpl.java:205)
	... 38 more

**Comment by acuevas-dgtic** [comment]
Si ve de custòdia s'han de demanar les matadades com es fa amb els fitxers adjunts
