### ISSUE TITLE
Error al donar d'alta una comunicacio SIR

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/notib#844]
Al fer una comunicacio SIR, el nom del destinatari es massa llarg: EA0041725 - Dirección Territorial Inspección de Trabajo y Seguridad Social de Illes Balears-Inspección Provincial Trabajo y Seguridad Social de Illes Balears.

Acaba amb un error de base de dades:
at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1384)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3730)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3710)
	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at org.jboss.ironjacamar.jdbcadapters@1.4.11.Final-redhat-00001//org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate(WrappedPreparedStatement.java:537)
	at deployment.notib.ear//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 284 more
Caused by: Error : 12899, Position : 326, Sql = insert into not_persona (createdBy_codi, createdDate, lastModifiedBy_codi, lastModifiedDate, cod_entitat_desti, document_tipus, email, notificacio_env_id, incapacitat, interessattipus, llinatge1, llinatge2, nif, nom, rao_social, telefon, id) values (:1 , :2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 , :10 , :11 , :12 , :13 , :14 , :15 , :16 , :17 ), OriginalSql = insert into not_persona (createdBy_codi, createdDate, lastModifiedBy_codi, lastModifiedDate, cod_entitat_desti, document_tipus, email, notificacio_env_id, incapacitat, interessattipus, llinatge1, llinatge2, nif, nom, rao_social, telefon, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), Error Msg = ORA-12899: value too large for column "NOTIB"."NOT_PERSONA"."RAO_SOCIAL" (actual: 145, maximum: 100)

	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 300 more

**Comment by acuevas-dgtic** [comment]
Sigue produciéndose el error en la rc39

**Comment by acuevas-dgtic** [comment]
Continua produciéndose en la rc40

**Comment by acuevas-dgtic** [comment]
Solucionado en la rc40
