### ISSUE TITLE
Error al actualitzar l'estat d'un enviament

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#845]
Si pitjes en el botó "Refrescar Estat" dóna un error:

![image](https://github.com/GovernIB/notib/assets/58417501/4f24452f-d021-4bbe-8657-27df5bc209d5)

```
java.lang.NullPointerException
	at deployment.notib.ear//es.caib.notib.logic.helper.WsClientHelper.generarClientWs(WsClientHelper.java:62)
	at deployment.notib.ear//es.caib.notib.logic.helper.NotificaV2Helper.getSincronizarEnvioWs(NotificaV2Helper.java:756)
	at deployment.notib.ear//es.caib.notib.logic.helper.NotificaV2Helper.getNotificaResultadoInfoEnvio(NotificaV2Helper.java:309)
	at deployment.notib.ear//es.caib.notib.logic.helper.NotificaV2Helper.enviamentRefrescarEstat(NotificaV2Helper.java:258)
	at deployment.notib.ear//es.caib.notib.logic.helper.NotificaV2Helper.enviamentRefrescarEstat(NotificaV2Helper.java:217)
	at deployment.notib.ear.notib-ejb.jar//es.caib.notib.logic.helper.NotificaV2Helper$$FastClassBySpringCGLIB$$680d6518.invoke(<generated>)
	at deployment.notib.ear//org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at deployment.notib.ear//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at deployment.notib....
```

**Comment by acuevas-dgtic** [comment]
Solucionado. Faltaba añadir una propiedad
