### ISSUE TITLE
Error de validació de signatures persistent en l'entorn de serveis estables

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#872]
Tenim que estar modificant constantment el valor d'una propietat en el plugin de validació de firmes per que funcioni.

```
java.io.FileNotFoundException: ./xmlTemplates/DSSVerifyRequest_V1.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.(FileInputStream.java:157)
	at java.base/java.io.FileReader.(FileReader.java:75)
	at deployment.notib.ear//es.gob.afirma.transformers.TransformersFacade.getXmlRequestFileByRequestType(TransformersFacade.java:134)
	at deployment.notib.ear//es.gob.afirma.transformers.xmlTransformers.DSSXmlTransformer.transform(DSSXmlTransformer.java:120)
	at jdk.internal.reflect.GeneratedMethodAccessor766.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at deployment.notib.ear//es.gob.afirma.transformers.TransformersFacade.invokeCommonXmlTransf(TransformersFacade.java:351)
	at deployment.notib.ear//es.gob.afirma.transformers.TransformersFacade.generateXml(TransformersFacade.java:247)
	at deployment.notib.ear//org.fundaciobit.plugins.validatesignature.afirmacxf.AfirmaCxfValidateSignaturePlugin.validateSignature(AfirmaCxfValidateSignaturePlugin.java:690)
	at deployment.notib.ear//es.caib.notib.logic.helper.PluginHelper.detectSignedAttachedUsingValidateSignaturePlugin(PluginHelper.java:1760)
	at deployment.notib.ear//es.caib.notib.logic.service.NotificacioServiceImpl.checkIfSignedAttached(NotificacioServiceImpl.java:1635)
	at deployment.notib.ear.notib-ejb.jar//es.caib.notib.logic.service.NotificacioServiceImpl$$FastClassBySpringCGLIB$$6077e7a5.invoke()
	at deployment.notib.ear//org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at deployment.notib.ear//org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at deployment.notib.ear//org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.ja...
```

**Comment by acuevas-dgtic** [comment]
El error peristeix

**Comment by acuevas-dgtic** [comment]
Plugin configurat
