### ISSUE TITLE
Error al accedir al plugin de gestió documental per a obtenir el document amb id: certificacions/null

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#885]
En el monitor apareixen molt d'errors  de consulta d'estat des de l'atib

```
es.caib.notib.logic.intf.exception.SistemaExternException: Error al accedir al plugin de gestió documental per a obtenir el document amb id: certificacions/null
	at deployment.notib.ear//es.caib.notib.logic.helper.PluginHelper.gestioDocumentalGet(PluginHelper.java:735)
	at deployment.notib.ear//es.caib.notib.logic.service.ws.NotificacioServiceWsImplV2.consultaEstatEnviamentV2(NotificacioServiceWsImplV2.java:623)
	at deployment.notib.ear.notib-ejb.jar//es.caib.notib.logic.service.ws.NotificacioServiceWsImplV2$$FastClassBySpringCGLIB$$9ed911cb.invoke()
	at deployment.notib.ear//org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at deployment.notib.ear//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at deployment.notib.ear//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at deployment.notib.ear//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at deployment.notib.ear//org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at deployment.notib.ear//org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at deployment.notib.ear//org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at deployment.notib.ear//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at deployment.notib.ear//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at deployment.notib.ear//org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at deployment.notib.ear.notib-ejb.jar//es.caib.notib.logic.service.ws.NotificacioServiceWsImplV2$$Enha...

```

**Comment by acuevas-dgtic** [comment]
Cal tenir en compte que utilicen l'API REST, no el client Java.  Fan peticions de tipus: https://intranet.caib.es/notibapi/interna/notificacio/v2/consultaEstatEnviament/ID
